# Generated by Django 3.0.5 on 2020-04-10 11:29

import django.contrib.postgres.fields.citext
from django.contrib.postgres.operations import CITextExtension
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        CITextExtension(),
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    django.contrib.postgres.fields.citext.CITextField(
                        max_length=256, unique=True
                    ),
                ),
                ("ident", models.TextField(unique=True)),
                (
                    "minimum",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("added", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="PresetItem",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    django.contrib.postgres.fields.citext.CITextField(
                        max_length=256, unique=True
                    ),
                ),
                (
                    "measure",
                    models.IntegerField(
                        choices=[
                            (0, "Generic"),
                            (1, "Length"),
                            (2, "Mass"),
                            (3, "Volume"),
                        ],
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Record",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("added", models.DateTimeField(auto_now=True, db_index=True)),
                ("note", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "symbol",
                    django.contrib.postgres.fields.citext.CITextField(
                        max_length=64, unique=True
                    ),
                ),
                (
                    "plural",
                    django.contrib.postgres.fields.citext.CITextField(
                        blank=True, max_length=64, null=True, unique=True
                    ),
                ),
                (
                    "code",
                    django.contrib.postgres.fields.citext.CITextField(
                        blank=True, max_length=64, null=True, unique=True
                    ),
                ),
                (
                    "measure",
                    models.IntegerField(
                        choices=[
                            (0, "Generic"),
                            (1, "Length"),
                            (2, "Mass"),
                            (3, "Volume"),
                        ]
                    ),
                ),
                ("convert", models.DecimalField(decimal_places=6, max_digits=12)),
            ],
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.CheckConstraint(
                check=models.Q(convert__gt=0), name="check_unit_convert_positive"
            ),
        ),
        migrations.AddField(
            model_name="record",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="records",
                to="inventory.Item",
            ),
        ),
        migrations.AddField(
            model_name="item",
            name="unit",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.Unit"
            ),
        ),
        migrations.AddConstraint(
            model_name="record",
            constraint=models.CheckConstraint(
                check=models.Q(quantity__gte=0), name="check_item_quantity_not_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.CheckConstraint(
                check=models.Q(minimum__gte=0), name="check_item_minimum_not_negative"
            ),
        ),
    ]
