# Generated by Django 3.0.5 on 2020-04-29 09:09

from django.conf import settings
import django.contrib.postgres.fields.citext
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="item", name="added", field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="minimum",
            field=models.DecimalField(
                decimal_places=3,
                default=0,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=django.contrib.postgres.fields.citext.CITextField(max_length=256),
        ),
        migrations.AlterField(
            model_name="item", name="ident", field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="item",
            name="unit",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.Unit",
            ),
        ),
        migrations.AlterField(
            model_name="record",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="unit",
            name="convert",
            field=models.DecimalField(
                decimal_places=6,
                max_digits=12,
                validators=[inventory.models.validate_gt_zero],
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("user", "name"), name="unique_item_user_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="item",
            constraint=models.UniqueConstraint(
                fields=("user", "ident"), name="unique_item_user_ident"
            ),
        ),
    ]
